package me.hoonick.tsingtao.blind.infrastructure.rest.blind.dto

import me.hoonick.tsingtao.blind.domain.BlindProfile

data class BlindProfileResponse(
    val result: Boolean,
    val code: String,
    val profileData: List<Profile>,
    val accessList: List<Any>,
    val fileList: List<FileData>,
) {
    fun toBlindProfile(): BlindProfile {
        val profileData = this.profileData.get(0)
        return BlindProfile(
            phone = profileData.phone,
            nickname = profileData.nick_name,
            birthday = profileData.birth_day,
            job = profileData.job,
            work = "${profileData.work1} + ${profileData.work2} + ${profileData.work3}",
            school = profileData.school1,
            tall = profileData.tall,
            smoke = profileData.smoke != 1,
            lastLoginDate = profileData.last_logindate,
            regDate = profileData.reg_date,
            getLikeCount = profileData.get_like_cnt,
            sendLikeCount = profileData.send_like_cnt,
            grade = profileData.grade,
            selfIntro = profileData.self_intro,
            address = "${profileData.sido_kr} ${profileData.gugun_kr}",
            workAddress = "${profileData.work_sido_kr} ${profileData.work_gugun_kr}",
            images = fileList.map {
                "https://www.badaduo.net:18114/files/${it.file_path}${it.file_name}"
            }
        )

    }

}

data class FileData(
    val file_seq: Int,
    val target_type: String,
    val target_key: String,
    val file_type: String,
    val file_size: Int,
    val file_path: String,
    val file_name: String,
    val file_extension: String,
    val file_width: Int,
    val file_height: Int,
    val thumb_path: String,
    val thumb_name: String,
    val thumb_extension: String,
    val thumb_width: Int,
    val thumb_height: Int,
    val mov_playtime: String?,
    val user_id: String,
    val reg_date: String,
    val sort: Int,
) {

}

data class Profile(
    val user_id: String,
    val recommender_id: String,
    val recommender_rel: Int,
    val phone: String,
    val match_num: String,
    val nick_name: String,
    val user_name: String?,
    val gender: String,
    val birth_day: String,
    val job: String,
    val work: String,
    val work1: String,
    val work2: String,
    val work3: String,
    val school: String,
    val school1: String,
    val school2: String,
    val school3: String,
    val gugun_code: String,
    val work_gugun_code: String,
    val blood_type: String,
    val tall: Int,
    val body_type: Int,
    val character1: Int,
    val character2: Int,
    val character3: Int,
    val believe: Int,
    val alcol: Int,
    val smoke: Int,
    val has_car: Int,
    val status: Int,
    val deny_cnt: Int,
    val deny_cause: String?,
    val deny_date: String?,
    val last_logindate: String,
    val reg_date: String,
    val agree_date: String,
    val agree_black: Int,
    val agree_black_date: String?,
    val heart: Int,
    val img: String,
    val img_thumb: String,
    val use_match: Int,
    val match_cnt: Int,
    val os_type: String,
    val pushkey: String,
    val pushset: Int,
    val same_company: Int,
    val answer: String,
    val server_id: String,
    val session_id: String?,
    val login_status: Int,
    val last_chat_logindate: String?,
    val user_type: Int,
    val get_like_cnt: Int,
    val send_like_cnt: Int,
    val get_favorite_cnt: Int,
    val send_favorite_cnt: Int,
    val comment: String,
    val grade: String,
    val withdraw_cause: String?,
    val withdraw_date: String?,
    val self_intro: String,
    val change_date: String,
    val change_cnt: Int,
    val est_user: Int,
    val est_npb: Int,
    val est_score: Int,
    val login_counter: Int,
    val auth_name: String?,
    val auth_phone: String?,
    val auth_date: String?,
    val sido_kr: String,
    val gugun_kr: String,
    val work_sido_kr: String,
    val work_gugun_kr: String,
    val recommender_code: String,
    val recommender_name: String,
    val is_like: Int,
    val my_like_type: String?,
    val my_like_msg: String?,
    val read_like_date: String?,
    val like_me: Int,
    val like_me_type: String?,
    val like_me_msg: String?,
    val is_favorite: Int,
    val is_block: Int,
    val has_profile: Int,
    val birth_day_string: String,
    val age_string: String,
) {

}
